package net.capozi.maisonnette.foundation;

import devv.capozi.zip.common.index.Registrar;
import net.capozi.maisonnette.Maisonnette;
import net.capozi.maisonnette.common.block.BookStackBlock;
import net.capozi.maisonnette.common.block.BulbBlock;
import net.capozi.maisonnette.common.block.MosaicBlock;
import net.capozi.maisonnette.common.block.SeatBlock;
import net.capozi.maisonnette.common.item.MosaicTileItem;
import net.capozi.maisonnette.server.world.generator.OrangeWillowSaplingGenerator;
import net.capozi.maisonnette.server.world.generator.RedWillowSaplingGenerator;
import net.capozi.maisonnette.server.world.generator.YellowWillowSaplingGenerator;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.minecraft.block.*;
import net.minecraft.block.AbstractBlock.OffsetType;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.util.Identifier;

import static net.capozi.maisonnette.common.block.BulbBlock.LIT;

public interface BlockInit {
	static void init() {
        blockRegistrar.setRegistries(blockRegistrar.entries, blockRegistrar.registry_consumer);
        blockItemRegistrar.setRegistries(blockItemRegistrar.entries, blockItemRegistrar.registry_consumer);
    }
    BlockSetType WILLOW_SET_TYPE = new BlockSetType("willow");
    WoodType WILLOW_WOOD_TYPE = new WoodType("willow", WILLOW_SET_TYPE);
    Registrar<Block> blockRegistrar = new Registrar<>(Maisonnette.MOD_ID, Registries.BLOCK);
    Registrar<Item> blockItemRegistrar = new Registrar<>(Maisonnette.MOD_ID, Registries.ITEM);
    Block MOSAIC = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "mosaic_tiles"), new MosaicBlock(FabricBlockSettings.copyOf(Blocks.BRICKS)));
    Block BOOK_STACK = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "book_stack"), new BookStackBlock(FabricBlockSettings.copyOf(Blocks.BAMBOO).sounds(SoundInit.BOOK_STACK_SOUNDS).nonOpaque().offset(OffsetType.NONE).burnable()));
    Block CALCITE_STAIRS = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "calcite_stairs"), new StairsBlock(Blocks.CALCITE.getDefaultState(), FabricBlockSettings.copyOf(Blocks.GRANITE_STAIRS)));
    Block CALCITE_SLAB = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "calcite_slab"), new SlabBlock(FabricBlockSettings.copyOf(Blocks.GRANITE_SLAB)));
    Block CALCITE_WALL = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "calcite_wall"), new WallBlock(FabricBlockSettings.copyOf(Blocks.GRANITE_WALL)));
    Block CALCITE_BUTTON = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "calcite_button"), new ButtonBlock(FabricBlockSettings.copyOf(Blocks.POLISHED_BLACKSTONE_BUTTON), BlockSetType.STONE, 10, false));
    Block TUFF_STAIRS = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "tuff_stairs"), new StairsBlock(Blocks.TUFF.getDefaultState(), FabricBlockSettings.copyOf(Blocks.TUFF)));
    Block TUFF_SLAB = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "tuff_slab"), new SlabBlock(FabricBlockSettings.copyOf(Blocks.TUFF)));
    Block TUFF_WALL = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "tuff_wall"), new WallBlock(FabricBlockSettings.copyOf(Blocks.TUFF)));
    Block TUFF_BUTTON = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "tuff_button"), new ButtonBlock(FabricBlockSettings.copyOf(Blocks.POLISHED_BLACKSTONE_BUTTON), BlockSetType.STONE, 10, false));
    Block COPPER_TORCHBULB = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "copper_torchbulb"), new BulbBlock(Oxidizable.OxidationLevel.UNAFFECTED, FabricBlockSettings.copyOf(Blocks.COPPER_BLOCK).luminance(state -> state.get(LIT) ? 15 : 0)));
    Block EXPOSED_COPPER_TORCHBULB = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "exposed_copper_torchbulb"), new BulbBlock(Oxidizable.OxidationLevel.EXPOSED, FabricBlockSettings.copyOf(Blocks.COPPER_BLOCK).luminance(state -> state.get(LIT) ? 12 : 0)));
    Block WEATHERED_COPPER_TORCHBULB = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "weathered_copper_torchbulb"), new BulbBlock(Oxidizable.OxidationLevel.WEATHERED, FabricBlockSettings.copyOf(Blocks.COPPER_BLOCK).luminance(state -> state.get(LIT) ? 8 : 0)));
    Block OXIDIZED_COPPER_TORCHBULB = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "oxidized_copper_torchbulb"), new BulbBlock(Oxidizable.OxidationLevel.OXIDIZED, FabricBlockSettings.copyOf(Blocks.COPPER_BLOCK).luminance(state -> state.get(LIT) ? 4 : 0)));
    Block WAXED_COPPER_TORCHBULB = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "waxed_copper_torchbulb"), new BulbBlock(Oxidizable.OxidationLevel.UNAFFECTED, FabricBlockSettings.copyOf(Blocks.COPPER_BLOCK).luminance(state -> state.get(LIT) ? 15 : 0)));
    Block WAXED_EXPOSED_COPPER_TORCHBULB = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "waxed_exposed_copper_torchbulb"), new BulbBlock(Oxidizable.OxidationLevel.EXPOSED, FabricBlockSettings.copyOf(Blocks.COPPER_BLOCK).luminance(state -> state.get(LIT) ? 12 : 0)));
    Block WAXED_WEATHERED_COPPER_TORCHBULB = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "waxed_weathered_copper_torchbulb"), new BulbBlock(Oxidizable.OxidationLevel.WEATHERED, FabricBlockSettings.copyOf(Blocks.COPPER_BLOCK).luminance(state -> state.get(LIT) ? 8 : 0)));
    Block WAXED_OXIDIZED_COPPER_TORCHBULB = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "waxed_oxidized_copper_torchbulb"), new BulbBlock(Oxidizable.OxidationLevel.OXIDIZED, FabricBlockSettings.copyOf(Blocks.COPPER_BLOCK).luminance(state -> state.get(LIT) ? 4 : 0)));
    Block WHITE_SEAT = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "white_seat"), new SeatBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB).sounds(BlockSoundGroup.NETHER_WOOD)));
    Block ORANGE_SEAT = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "orange_seat"), new SeatBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB).sounds(BlockSoundGroup.NETHER_WOOD)));
    Block LIGHT_BLUE_SEAT = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "light_blue_seat"), new SeatBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB).sounds(BlockSoundGroup.NETHER_WOOD)));
    Block YELLOW_SEAT = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "yellow_seat"), new SeatBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB).sounds(BlockSoundGroup.NETHER_WOOD)));
    Block LIME_SEAT = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "lime_seat"), new SeatBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB).sounds(BlockSoundGroup.NETHER_WOOD)));
    Block PINK_SEAT = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "pink_seat"), new SeatBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB).sounds(BlockSoundGroup.NETHER_WOOD)));
    Block GRAY_SEAT = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "gray_seat"), new SeatBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB).sounds(BlockSoundGroup.NETHER_WOOD)));
    Block LIGHT_GRAY_SEAT = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "light_gray_seat"), new SeatBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB).sounds(BlockSoundGroup.NETHER_WOOD)));
    Block CYAN_SEAT = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "cyan_seat"), new SeatBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB).sounds(BlockSoundGroup.NETHER_WOOD)));
    Block BLUE_SEAT = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "blue_seat"), new SeatBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB).sounds(BlockSoundGroup.NETHER_WOOD)));
    Block PURPLE_SEAT = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "purple_seat"), new SeatBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB).sounds(BlockSoundGroup.NETHER_WOOD)));
    Block BROWN_SEAT = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "brown_seat"), new SeatBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB).sounds(BlockSoundGroup.NETHER_WOOD)));
    Block GREEN_SEAT = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "green_seat"), new SeatBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB).sounds(BlockSoundGroup.NETHER_WOOD)));
    Block RED_SEAT = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "red_seat"), new SeatBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB).sounds(BlockSoundGroup.NETHER_WOOD)));
    Block BLACK_SEAT = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "black_seat"), new SeatBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB).sounds(BlockSoundGroup.NETHER_WOOD)));
    Block MAGENTA_SEAT = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "magenta_seat"), new SeatBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB).sounds(BlockSoundGroup.NETHER_WOOD)));
    Block WILLOW_LOG = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_log"), new PillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_LOG).strength(4f)));
    Block STRIPPED_WILLOW_LOG = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "stripped_willow_log"), new PillarBlock(FabricBlockSettings.copyOf(Blocks.STRIPPED_OAK_LOG).strength(4f)));
    Block WILLOW_WOOD = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_wood"), new PillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_WOOD).strength(4f)));
    Block STRIPPED_WILLOW_WOOD = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "stripped_willow_wood"), new PillarBlock(FabricBlockSettings.copyOf(Blocks.STRIPPED_OAK_WOOD).strength(4f)));
    Block WILLOW_PLANKS = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_planks"), new Block(FabricBlockSettings.copyOf(Blocks.OAK_PLANKS).strength(4f)));
    Block RED_WILLOW_LEAVES = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "red_willow_leaves"), new LeavesBlock(FabricBlockSettings.copyOf(Blocks.OAK_LEAVES).nonOpaque()));
    Block ORANGE_WILLOW_LEAVES = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "orange_willow_leaves"), new LeavesBlock(FabricBlockSettings.copyOf(Blocks.OAK_LEAVES).nonOpaque()));
    Block YELLOW_WILLOW_LEAVES = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "yellow_willow_leaves"), new LeavesBlock(FabricBlockSettings.copyOf(Blocks.OAK_LEAVES).nonOpaque()));
    Block RED_WILLOW_SAPLING = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "red_willow_sapling"), new SaplingBlock(new RedWillowSaplingGenerator(), FabricBlockSettings.copyOf(Blocks.OAK_SAPLING)));
    Block ORANGE_WILLOW_SAPLING = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "orange_willow_sapling"), new SaplingBlock(new OrangeWillowSaplingGenerator(), FabricBlockSettings.copyOf(Blocks.OAK_SAPLING)));
    Block YELLOW_WILLOW_SAPLING = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "yellow_willow_sapling"), new SaplingBlock(new YellowWillowSaplingGenerator(), FabricBlockSettings.copyOf(Blocks.OAK_SAPLING)));
    Block WILLOW_SLAB = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_slab"), new SlabBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB)));
    Block WILLOW_STAIRS = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_stairs"), new StairsBlock(Blocks.OAK_STAIRS.getDefaultState(), FabricBlockSettings.copyOf(Blocks.OAK_STAIRS)));
    Block WILLOW_FENCE = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_fence"), new FenceBlock(FabricBlockSettings.copyOf(Blocks.OAK_FENCE)));
    Block WILLOW_FENCE_GATE = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_fence_gate"), new FenceGateBlock(FabricBlockSettings.copyOf(Blocks.OAK_FENCE_GATE), WILLOW_WOOD_TYPE));
    Block WILLOW_BUTTON = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_button"), new ButtonBlock(FabricBlockSettings.copyOf(Blocks.POLISHED_BLACKSTONE_BUTTON), WILLOW_SET_TYPE, 10, true));
    Block WILLOW_PRESSURE_PLATE = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_pressure_plate"), new PressurePlateBlock(PressurePlateBlock.ActivationRule.EVERYTHING, FabricBlockSettings.copyOf(Blocks.OAK_PRESSURE_PLATE), WILLOW_SET_TYPE));
    Block WILLOW_DOOR = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_door"), new DoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_DOOR), WILLOW_SET_TYPE));
    Block WILLOW_TRAPDOOR = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_trapdoor"), new TrapdoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_DOOR), WILLOW_SET_TYPE));
    Block CHARRED_LOG = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_log"), new PillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_LOG).strength(4f)));
    Block STRIPPED_CHARRED_LOG = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "stripped_charred_log"), new PillarBlock(FabricBlockSettings.copyOf(Blocks.STRIPPED_OAK_LOG).strength(4f)));
    Block CHARRED_WOOD = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_wood"), new PillarBlock(FabricBlockSettings.copyOf(Blocks.OAK_WOOD).strength(4f)));
    Block STRIPPED_CHARRED_WOOD = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "stripped_charred_wood"), new PillarBlock(FabricBlockSettings.copyOf(Blocks.STRIPPED_OAK_WOOD).strength(4f)));
    Block CHARRED_PLANKS = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_planks"), new Block(FabricBlockSettings.copyOf(Blocks.OAK_PLANKS).strength(4f)));
    Block CHARRED_SLAB = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_slab"), new SlabBlock(FabricBlockSettings.copyOf(Blocks.OAK_SLAB)));
    Block CHARRED_STAIRS = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_stairs"), new StairsBlock(Blocks.OAK_STAIRS.getDefaultState(), FabricBlockSettings.copyOf(Blocks.OAK_STAIRS)));
    Block CHARRED_FENCE = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_fence"), new FenceBlock(FabricBlockSettings.copyOf(Blocks.OAK_FENCE)));
    Block CHARRED_FENCE_GATE = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_fence_gate"), new FenceGateBlock(FabricBlockSettings.copyOf(Blocks.OAK_FENCE_GATE), WILLOW_WOOD_TYPE));
    Block CHARRED_BUTTON = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_button"), new ButtonBlock(FabricBlockSettings.copyOf(Blocks.POLISHED_BLACKSTONE_BUTTON), WILLOW_SET_TYPE, 10, true));
    Block CHARRED_PRESSURE_PLATE = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_pressure_plate"), new PressurePlateBlock(PressurePlateBlock.ActivationRule.EVERYTHING, FabricBlockSettings.copyOf(Blocks.OAK_PRESSURE_PLATE), WILLOW_SET_TYPE));
    Block CHARRED_DOOR = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_door"), new DoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_DOOR), WILLOW_SET_TYPE));
    Block CHARRED_TRAPDOOR = blockRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_trapdoor"), new TrapdoorBlock(FabricBlockSettings.copyOf(Blocks.OAK_DOOR), WILLOW_SET_TYPE));
    Item MOSAIC_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "mosaic_tiles"), new MosaicTileItem(MOSAIC, new FabricItemSettings()));
    Item CALCITE_STAIRS_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "calcite_stairs"), new BlockItem(CALCITE_STAIRS, new FabricItemSettings()));
    Item CALCITE_SLAB_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "calcite_slab"), new BlockItem(CALCITE_SLAB, new FabricItemSettings()));
    Item CALCITE_WALL_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "calcite_wall"), new BlockItem(CALCITE_WALL, new FabricItemSettings()));
    Item CALCITE_BUTTON_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "calcite_button"), new BlockItem(CALCITE_BUTTON, new FabricItemSettings()));
    Item TUFF_STAIRS_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "tuff_stairs"), new BlockItem(TUFF_STAIRS, new FabricItemSettings()));
    Item TUFF_SLAB_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "tuff_slab"), new BlockItem(TUFF_SLAB, new FabricItemSettings()));
    Item TUFF_WALL_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "tuff_wall"), new BlockItem(TUFF_WALL, new FabricItemSettings()));
    Item TUFF_BUTTON_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "tuff_button"), new BlockItem(TUFF_BUTTON, new FabricItemSettings()));
    Item COPPER_TORCHBULB_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "copper_torchbulb"), new BlockItem(COPPER_TORCHBULB, new FabricItemSettings()));
    Item EXPOSED_COPPER_TORCHBULB_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "exposed_copper_torchbulb"), new BlockItem(EXPOSED_COPPER_TORCHBULB, new FabricItemSettings()));
    Item WEATHERED_COPPER_TORCHBULB_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "weathered_copper_torchbulb"), new BlockItem(WEATHERED_COPPER_TORCHBULB, new FabricItemSettings()));
    Item OXIDIZED_COPPER_TORCHBULB_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "oxidized_copper_torchbulb"), new BlockItem(OXIDIZED_COPPER_TORCHBULB, new FabricItemSettings()));
    Item WAXED_COPPER_TORCHBULB_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "waxed_copper_torchbulb"), new BlockItem(WAXED_COPPER_TORCHBULB, new FabricItemSettings()));
    Item WAXED_EXPOSED_COPPER_TORCHBULB_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "waxed_exposed_copper_torchbulb"), new BlockItem(WAXED_EXPOSED_COPPER_TORCHBULB, new FabricItemSettings()));
    Item WAXED_WEATHERED_COPPER_TORCHBULB_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "waxed_weathered_copper_torchbulb"), new BlockItem(WAXED_WEATHERED_COPPER_TORCHBULB, new FabricItemSettings()));
    Item WAXED_OXIDIZED_COPPER_TORCHBULB_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "waxed_oxidized_copper_torchbulb"), new BlockItem(WAXED_OXIDIZED_COPPER_TORCHBULB, new FabricItemSettings()));
    Item WHITE_SEAT_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "white_seat"), new BlockItem(WHITE_SEAT, new FabricItemSettings()));
    Item ORANGE_SEAT_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "orange_seat"), new BlockItem(ORANGE_SEAT, new FabricItemSettings()));
    Item LIGHT_BLUE_SEAT_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "light_blue_seat"), new BlockItem(LIGHT_BLUE_SEAT, new FabricItemSettings()));
    Item YELLOW_SEAT_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "yellow_seat"), new BlockItem(YELLOW_SEAT, new FabricItemSettings()));
    Item LIME_SEAT_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "lime_seat"), new BlockItem(LIME_SEAT, new FabricItemSettings()));
    Item PINK_SEAT_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "pink_seat"), new BlockItem(PINK_SEAT, new FabricItemSettings()));
    Item GRAY_SEAT_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "gray_seat"), new BlockItem(GRAY_SEAT, new FabricItemSettings()));
    Item LIGHT_GRAY_SEAT_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "light_gray_seat"), new BlockItem(LIGHT_GRAY_SEAT, new FabricItemSettings()));
    Item CYAN_SEAT_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "cyan_seat"), new BlockItem(CYAN_SEAT, new FabricItemSettings()));
    Item BLUE_SEAT_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "blue_seat"), new BlockItem(BLUE_SEAT, new FabricItemSettings()));
    Item PURPLE_SEAT_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "purple_seat"), new BlockItem(PURPLE_SEAT, new FabricItemSettings()));
    Item BROWN_SEAT_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "brown_seat"), new BlockItem(BROWN_SEAT, new FabricItemSettings()));
    Item GREEN_SEAT_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "green_seat"), new BlockItem(GREEN_SEAT, new FabricItemSettings()));
    Item RED_SEAT_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "red_seat"), new BlockItem(RED_SEAT, new FabricItemSettings()));
    Item BLACK_SEAT_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "black_seat"), new BlockItem(BLACK_SEAT, new FabricItemSettings()));
    Item MAGENTA_SEAT_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "magenta_seat"), new BlockItem(MAGENTA_SEAT, new FabricItemSettings()));
    Item WILLOW_LOG_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_log"), new BlockItem(WILLOW_LOG, new FabricItemSettings()));
    Item STRIPPED_WILLOW_LOG_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "stripped_willow_log"), new BlockItem(STRIPPED_WILLOW_LOG, new FabricItemSettings()));
    Item WILLOW_WOOD_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_wood"), new BlockItem(WILLOW_WOOD, new FabricItemSettings()));
    Item STRIPPED_WILLOW_WOOD_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "stripped_willow_wood"), new BlockItem(STRIPPED_WILLOW_WOOD, new FabricItemSettings()));
    Item WILLOW_PLANKS_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_planks"), new BlockItem(WILLOW_PLANKS, new FabricItemSettings()));
    Item RED_WILLOW_LEAVES_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "red_willow_leaves"), new BlockItem(RED_WILLOW_LEAVES, new FabricItemSettings()));
    Item ORANGE_WILLOW_LEAVES_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "orange_willow_leaves"), new BlockItem(ORANGE_WILLOW_LEAVES, new FabricItemSettings()));
    Item YELLOW_WILLOW_LEAVES_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "yellow_willow_leaves"), new BlockItem(YELLOW_WILLOW_LEAVES, new FabricItemSettings()));
    Item RED_WILLOW_SAPLING_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "red_willow_sapling"), new BlockItem(RED_WILLOW_SAPLING, new FabricItemSettings()));
    Item ORANGE_WILLOW_SAPLING_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "orange_willow_sapling"), new BlockItem(ORANGE_WILLOW_SAPLING, new FabricItemSettings()));
    Item YELLOW_WILLOW_SAPLING_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "yellow_willow_sapling"), new BlockItem(YELLOW_WILLOW_SAPLING, new FabricItemSettings()));
    Item WILLOW_SLAB_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_slab"), new BlockItem(WILLOW_SLAB, new FabricItemSettings()));
    Item WILLOW_STAIRS_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_stairs"), new BlockItem(WILLOW_STAIRS, new FabricItemSettings()));
    Item WILLOW_FENCE_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_fence"), new BlockItem(WILLOW_FENCE, new FabricItemSettings()));
    Item WILLOW_FENCE_GATE_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_fence_gate"), new BlockItem(WILLOW_FENCE_GATE, new FabricItemSettings()));
    Item WILLOW_BUTTON_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_button"), new BlockItem(WILLOW_BUTTON, new FabricItemSettings()));
    Item WILLOW_PRESSURE_PLATE_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_pressure_plate"), new BlockItem(WILLOW_PRESSURE_PLATE, new FabricItemSettings()));
    Item WILLOW_DOOR_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_door"), new BlockItem(WILLOW_DOOR, new FabricItemSettings()));
    Item WILLOW_TRAPDOOR_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "willow_trapdoor"), new BlockItem(WILLOW_TRAPDOOR, new FabricItemSettings()));
    Item CHARRED_LOG_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_log"), new BlockItem(CHARRED_LOG, new FabricItemSettings()));
    Item STRIPPED_CHARRED_LOG_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "stripped_charred_log"), new BlockItem(STRIPPED_CHARRED_LOG, new FabricItemSettings()));
    Item CHARRED_WOOD_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_wood"), new BlockItem(CHARRED_WOOD, new FabricItemSettings()));
    Item STRIPPED_CHARRED_WOOD_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "stripped_charred_wood"), new BlockItem(STRIPPED_CHARRED_WOOD, new FabricItemSettings()));
    Item CHARRED_PLANKS_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_planks"), new BlockItem(CHARRED_PLANKS, new FabricItemSettings()));
    Item CHARRED_SLAB_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_slab"), new BlockItem(CHARRED_SLAB, new FabricItemSettings()));
    Item CHARRED_STAIRS_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_stairs"), new BlockItem(CHARRED_STAIRS, new FabricItemSettings()));
    Item CHARRED_FENCE_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_fence"), new BlockItem(CHARRED_FENCE, new FabricItemSettings()));
    Item CHARRED_FENCE_GATE_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_fence_gate"), new BlockItem(CHARRED_FENCE_GATE, new FabricItemSettings()));
    Item CHARRED_BUTTON_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_button"), new BlockItem(CHARRED_BUTTON, new FabricItemSettings()));
    Item CHARRED_PRESSURE_PLATE_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_pressure_plate"), new BlockItem(CHARRED_PRESSURE_PLATE, new FabricItemSettings()));
    Item CHARRED_DOOR_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_door"), new BlockItem(CHARRED_DOOR, new FabricItemSettings()));
    Item CHARRED_TRAPDOOR_ITEM = blockItemRegistrar.add(new Identifier(Maisonnette.MOD_ID, "charred_trapdoor"), new BlockItem(CHARRED_TRAPDOOR, new FabricItemSettings()));
}